apiVersion: v1
kind: ServiceAccount
metadata:
  name: cxe-complexity-profile-executor
  namespace: {{ include "algocrack.namespace" . }}
  labels:
    {{- include "algocrack.labels" . | nindent 4 }}
    {{- include "algocrack.componentLabel" "code-execution-engine" | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cxe-complexity-profile-execution-job
  namespace: {{ include "algocrack.namespace" . }}
  labels:
    {{- include "algocrack.labels" . | nindent 4 }}
    {{- include "algocrack.componentLabel" "code-execution-engine" | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      component: complexity-profile-job
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.complexityProfile.networkPolicy.dnsNamespace | default "kube-system" }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.complexityProfile.networkPolicy.dnsPodLabels | nindent 14 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
