{{- if .Values.services.codeExecutionEngine.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: code-execution-engine
  namespace: {{ include "algocrack.namespace" . }}
  labels:
    {{- include "algocrack.labels" . | nindent 4 }}
    {{- include "algocrack.componentLabel" "code-execution-engine" | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-execution-engine
  minReplicas: {{ .Values.services.codeExecutionEngine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.codeExecutionEngine.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.codeExecutionEngine.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
