{{- if .Values.services.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: {{ include "algocrack.namespace" . }}
  labels:
    {{- include "algocrack.labels" . | nindent 4 }}
    {{- include "algocrack.componentLabel" "frontend" | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.services.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.frontend.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.frontend.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
