{{- if not .Values.secrets.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: algocrack-app-secrets
  namespace: {{ include "algocrack.namespace" . }}
  labels:
    {{- include "algocrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.auth.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  JWT_EXPIRY: {{ .Values.auth.jwt.expirySeconds | quote }}
  COOKIE_EXPIRY: {{ .Values.auth.jwt.cookieExpirySeconds | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.auth.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret | quote }}
{{- end }}
